@startuml

Interface BnfTree
{

}
class Lexer
{

}

class Sequence
{

}

Lexer -up-> Sequence
Lexer -up-> Terminal
Lexer -up-> Group
Lexer -up-> Repeat
Lexer -up-> Optional
Lexer -up-> Exception

Sequence -up-> BnfTree
Terminal -up-> BnfTree
Group -up-> BnfTree : ()
Repeat -up-> BnfTree : {}
Optional -up-> BnfTree : []
Alternate -up-> BnfTree : |
Exception -up-> BnfTree : -

|-[NonTerminal]-(Terminal)-|

Title	    bnfTitle	    Returns the title string between ticks quote
Diagram	    bnfDiagram	    Returns the result string 
Sequence	bnfSequence	    Returns Childs separated by commas between parenthesis (,,)
Stack   	bnfStack	    Returns Childs separated by commas and linefeed between parenthesis
Choice	    bnfChoice	    Returns Childs separated by vertical line and linefeed between parenthesis (||)
Optional	bnfOptional	    Returns Child with appended ? []
OneOrMore	bnfOneOrMore	Returns Child1 ( Child2 Child1 )* or Child+
ZeroOrMore	bnfZeroOrMore	Returns Child1 ( Child2 Child1 )* or Child* {}
Terminal	bnfTerminal	    Returns single quoted Child ""
NonTerminal	bnfNonTerminal	Returns Child between leading and trailing space 
Comment	    bnfComment	    Returns string between ticks ''
Skip	    bnfSkip	        Returns <Skip>


@enduml