@startuml
title Mediator Pattern

Colleague1 --> Mediator : mediate(c1)
activate Colleague1
    activate Mediator
        Colleague1 <-- Mediator : getState()
            activate Colleague1
            deactivate Colleague1
        Mediator --> Colleague2 : action2()
            activate Colleague2
            deactivate Colleague2
    deactivate Mediator 
deactivate Colleague1

Colleague2 --> Mediator : mediate(c2)
activate Colleague2
    activate Mediator
        Colleague2 <-- Mediator : getState()
            activate Colleague2
            deactivate Colleague2
        Mediator --> Colleague1 : action1()
            activate Colleague1
            deactivate Colleague1        
    deactivate Mediator 
deactivate Colleague2

@enduml
