@startuml

title "Elastic Search Update - Sequence Diagram"

actor hub
Database  SQL
hub -> SQL
return Id
Queue StorageQueue
hub -> StorageQueue : Save Id
Webjob -> StorageQueue : Get Id
return

Webjob -> SQL : Get Data
activate Webjob
return
Webjob -> SQL
return
Webjob -> SQL
return
deactivate Webjob
Database ElasticSearch
Webjob -> ElasticSearch : Send Data
return
hub -> ElasticSearch : Search
return

@enduml