@startuml Address

Interface IRequestHandler

'IRequestHandler <-- AddressFormsEditQuery
IRequestHandler <-- AddressFormQueryResult
IRequestHandler <-- AddressFormsViewQueryResult
IRequestHandler <|-- AddressFormsEditQueryHandler

AddressFormsBaseQuery <|-- AddressFormsViewQuery
IRequest <|-- AddressFormsViewQuery

AddressFormsBaseQuery <|-- AddressFormsEditQuery 
IRequest <|-- AddressFormsEditQuery
@enduml



