@startuml

title "SQL Integrated Change Tracking - Sequence Diagram"

activate hub
actor hub
Database  SQL
activate Webjob
Webjob -> SQL : Connect
hub -> SQL

Webjob -> SQL : Get Changes
return
Webjob -> SQL : Get Data
return
Database ElasticSearch
Webjob -> ElasticSearch : Send Data
return

Webjob -> SQL : Disconnect
deactivate Webjob
deactivate hub


@enduml