@startuml Template Masking

allow_mixing

Interface BaseDs
BaseDs <|-- OfferDs
BaseDs <|-- RequirementDs
BaseDs <|-- ActivityDs

Interface IDataSourceBuilder
IDataSourceBuilder : BuildOfferDS
IDataSourceBuilder : BuildRequirementDS
IDataSourceBuilder : BuildActivityDS

IDataSourceBuilder <|-- DataSourceBuilder
IDataSourceBuilder -right-> BaseDs

DataSourceBuilder : BuildOfferDS()
DataSourceBuilder : BuildRequirementDS()
DataSourceBuilder : BuildActivityDS()

DataSourceBuilder -up-> OfferDs
DataSourceBuilder -up-> RequirementDs
DataSourceBuilder -up-> ActivityDs

OfferDocumentGeneratorBehaviour : List<TemplateDataSource> DataSources
OfferDocumentGeneratorBehaviour : GetOffer()
OfferDocumentGeneratorBehaviour : GetRequirement()
OfferDocumentGeneratorBehaviour : GetActivity()

Interface IDocumentGeneratorBehaviour
IDocumentGeneratorBehaviour : List<TemplateDataSource> DataSources

IDocumentGeneratorBehaviour <|-- OfferDocumentGeneratorBehaviour
OfferDocumentGeneratorBehaviour -right-> IDataSourceBuilder

Interface ISecurityValidator
ISecurityValidator : GetVisibilityLevel<T>(Guid Id)
ISecurityValidator : CheckIsNotHidden<T>(Guid Id)

ISecurityValidator <|-- SecurityValidator
SecurityValidator : GetVisibilityLevel<T>(Guid Id)

OfferDocumentGeneratorBehaviour -left-> SecurityValidator

Database IReadGenericRepository
OfferDocumentGeneratorBehaviour --> IReadGenericRepository

@enduml