@startuml TextMessage

' Interfaces, Classes, Methods
Interface INotification
Interface INotificationHandler 
Class TextMessageOutboxedEvent
Class TextMessageOutboxedEventHandler
'Class TextMessageViewModel

INotification : mediate()
TextMessageOutboxedEventHandler : Handle() 

' Relationship
INotification <- INotificationHandler : mediator
INotification -[hidden]-> TextMessageOutboxedEventHandler

INotification <|-- TextMessageOutboxedEvent : Implements
INotificationHandler <|-- TextMessageOutboxedEventHandler : Implements
TextMessageOutboxedEvent -> TextMessageOutboxedEventHandler

note "En Queue Message" as n1
n1 .. TextMessageOutboxedEventHandler

' =======================

' Interfaces, Classes, Methods
Interface IRequest 
interface IRequestHandler
Class TextMessageCommandBase
Class TextMessageQueryHandler
Class CreateTextMessageCommandHandler

IRequest : mediate()
CreateTextMessageCommandHandler : Handle()

' Relationship
IRequest <- IRequestHandler : mediator
IRequest -[hidden]-> TextMessageQueryHandler

IRequest <|-- TextMessageCommandBase
IRequestHandler <|-- TextMessageQueryHandler : Implements
CreateTextMessageCommand -up-> CreateTextMessageCommandHandler
TextMessageQueryHandler <|-- CreateTextMessageCommandHandler : Implements
TextMessageCommand -up-> TextMessageCommandBase
TextMessageCommand -right-> CreateTextMessageCommandHandler

@enduml
