@startuml

title Web Display Contacts

object Activity
object ActivityWebnegotiator
object ActivityNegotiator
object ActivityDepartment

object User
object OrganisationalUnit

ActivityWebnegotiator --|> User 
ActivityWebnegotiator -up-|> Activity
ActivityDepartment --|> OrganisationalUnit 
ActivityNegotiator --|> User 
ActivityNegotiator -up-|> Activity
ActivityDepartment -up-|> Activity
User --|> OrganisationalUnit

User : Id
User : FirstName
User : LastName
User : EmailAddress
User : TelephoneNumber
User : ResponsibleForSaleOrLetNegotiatorDepartmentId

ActivityDepartment : Id
ActivityDepartment : ActivityId
ActivityDepartment : DepartmentId

ActivityNegotiator : Id
ActivityNegotiator : ActivityId
ActivityNegotiator : UserId
ActivityNegotiator : UserTypeId

ActivityWebnegotiator : Id
ActivityWebnegotiator : ActivityId
ActivityWebnegotiator : UserId
ActivityWebnegotiator : Order

Activity : Id
OrganisationalUnit : Id

@enduml