@startuml WOPI
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!define AzurePuml https://raw.githubusercontent.com/RicardoNiepel/Azure-PlantUML/release/2-1/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Databases/AzureCosmosDb.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Storage/AzureBlobStorage.puml
!includeurl AzurePuml/Web/AzureWebApp.puml
!includeurl AzurePuml/Security/AzureKeyVault.puml
!includeurl AzurePuml/DevOps/AzureApplicationInsights.puml
!includeurl AzurePuml/Networking/AzureTrafficManager.puml
!includeurl AzurePuml/Networking/AzureVPNGateway.puml
!includeurl AzurePuml/Networking/AzureVirtualNetwork.puml

LAYOUT_TOP_DOWN

Person(user, "Office Online", "*.wopihost.hub.knightfrank.com")
Container( disco, "Office Online\nServer", "Xml")
AzureTrafficManager( azTm, "Traffic Manager", "Traffic Manager")

frame "Northern Europe" as azRGNe {
    AzureWebApp( azWaNe, "WOPI Host", "Provides Office Online access to the blob store")
    AzureBlobStorage( azBSNe, "File Storage", "Office documents")
    AzureVPNGateway( azVpnNe, "VPN Gateway", "fred")
}

frame "Western Europe" as azRGwe{
    AzureVPNGateway( azVpnWe, "VPN Gateway", "fred")
    AzureBlobStorage( azBSWe, "File Storage(Copy)", "Office documents")
    AzureWebApp( azWaWe, "WOPI Host", "Provides Office Online access to the blob store")
}

System_Boundary(azGC, "Shared Components"){
    AzureActiveDirectory( azAd, "Active Directory", "App registration")
    AzureCosmosDb( azCDb, "Metadata", "Document Metadata")
    AzureKeyVault(azKv, "KeyVault", "KeyVault")
    AzureApplicationInsights( azAI, "Application Insights", "Application Insights")
}

azBSNe .right.> azBSWe

azTm --> azWaNe
azTm --> azWaWe
user --> azTm

azWaNe --> azGC
azWaWe --> azGC

azWaNe -up-> azVpnNe
azWaWe -up-> azVpnWe

azVpnNe --> disco
azVpnWe --> disco


@enduml
